// <auto-generated />
namespace JabbR.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserRoomSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRoomSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201305162215470_UserRoomSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
